/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jphoebe_demo_jni_JniExceptionDemo */

#ifndef _Included_edu_jphoebe_demo_jni_JniExceptionDemo
#define _Included_edu_jphoebe_demo_jni_JniExceptionDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_jphoebe_demo_jni_JniExceptionDemo
 * Method:    exception1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jphoebe_demo_jni_JniExceptionDemo_exception1
  (JNIEnv *, jobject);

/*
 * Class:     edu_jphoebe_demo_jni_JniExceptionDemo
 * Method:    exception2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jphoebe_demo_jni_JniExceptionDemo_exception2
  (JNIEnv *, jobject);

/*
 * Class:     edu_jphoebe_demo_jni_JniExceptionDemo
 * Method:    exception3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_jphoebe_demo_jni_JniExceptionDemo_exception3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
