/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_jphoebe_demo_jni_JniDemo */

#ifndef _Included_edu_jphoebe_demo_jni_JniDemo
#define _Included_edu_jphoebe_demo_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_jphoebe_demo_jni_JniDemo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_jphoebe_demo_jni_JniDemo_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_jphoebe_demo_jni_JniDemo
 * Method:    printByNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_jphoebe_demo_jni_JniDemo_printByNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_jphoebe_demo_jni_JniDemo
 * Method:    setCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_jphoebe_demo_jni_JniDemo_setCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
